#! /bin/sh

set -e

case "$1" in
start)
    echo -n "Starting attfotademo: "
    start-stop-daemon -S -b -x /usr/bin/attfotademo
    echo "done"
    ;;
  stop)
    echo -n "Stopping attfotademo: "
    start-stop-daemon -K -n /usr/bin/attfotademo
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage attfotademo{ start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
