#! /bin/sh
#
#Copyright (c) 2020 Quectel Wireless Solutions Co., Ltd. All Rights Reserved.
#Qualcomm Technologies Proprietary and Confidential.

# qcrild init.d script to start the qcrild daemon

#set -e

case "$1" in
    start)
        echo -n  "Starting qcrild: " > /dev/kmsg
        pids=`pidof qcrild`
        if [ -n "$pids" ]; then
            killall qcrild
        fi
        mkdir -p data/misc/radio
        qcrild &
        qcrild -c 2 &
        echo "done" > /dev/kmsg
        ;;
    stop)
        echo -n "Stopping qcrild: " > /dev/kmsg
        killall qcrild
        echo "done" > /dev/kmsg
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage $0 { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
