/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Fri May  8 16:19:29 2020. */

#ifndef PB_IMS_IMSIF_PB_H_INCLUDED
#define PB_IMS_IMSIF_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ims_MsgType {
    ims_MsgType_UNKNOWN = 0,
    ims_MsgType_REQUEST = 1,
    ims_MsgType_RESPONSE = 2,
    ims_MsgType_UNSOL_RESPONSE = 3
} ims_MsgType;
#define _ims_MsgType_MIN ims_MsgType_UNKNOWN
#define _ims_MsgType_MAX ims_MsgType_UNSOL_RESPONSE
#define _ims_MsgType_ARRAYSIZE ((ims_MsgType)(ims_MsgType_UNSOL_RESPONSE+1))

typedef enum _ims_MsgId {
    ims_MsgId_UNKNOWN_REQ = 0,
    ims_MsgId_REQUEST_IMS_REGISTRATION_STATE = 1,
    ims_MsgId_REQUEST_DIAL = 2,
    ims_MsgId_REQUEST_ANSWER = 3,
    ims_MsgId_REQUEST_HANGUP = 4,
    ims_MsgId_REQUEST_LAST_CALL_FAIL_CAUSE = 5,
    ims_MsgId_REQUEST_GET_CURRENT_CALLS = 6,
    ims_MsgId_REQUEST_HANGUP_WAITING_OR_BACKGROUND = 7,
    ims_MsgId_REQUEST_HANGUP_FOREGROUND_RESUME_BACKGROUND = 8,
    ims_MsgId_REQUEST_SWITCH_WAITING_OR_HOLDING_AND_ACTIVE = 9,
    ims_MsgId_REQUEST_CONFERENCE = 10,
    ims_MsgId_REQUEST_EXIT_EMERGENCY_CALLBACK_MODE = 11,
    ims_MsgId_REQUEST_EXPLICIT_CALL_TRANSFER = 12,
    ims_MsgId_REQUEST_DTMF = 13,
    ims_MsgId_REQUEST_DTMF_START = 14,
    ims_MsgId_REQUEST_DTMF_STOP = 15,
    ims_MsgId_REQUEST_UDUB = 16,
    ims_MsgId_REQUEST_MODIFY_CALL_INITIATE = 17,
    ims_MsgId_REQUEST_MODIFY_CALL_CONFIRM = 18,
    ims_MsgId_REQUEST_QUERY_CLIP = 19,
    ims_MsgId_REQUEST_GET_CLIR = 20,
    ims_MsgId_REQUEST_SET_CLIR = 21,
    ims_MsgId_REQUEST_QUERY_CALL_FORWARD_STATUS = 22,
    ims_MsgId_REQUEST_SET_CALL_FORWARD_STATUS = 23,
    ims_MsgId_REQUEST_QUERY_CALL_WAITING = 24,
    ims_MsgId_REQUEST_SET_CALL_WAITING = 25,
    ims_MsgId_REQUEST_IMS_REG_STATE_CHANGE = 26,
    ims_MsgId_REQUEST_SET_SUPP_SVC_NOTIFICATION = 27,
    ims_MsgId_REQUEST_ADD_PARTICIPANT = 28,
    ims_MsgId_REQUEST_QUERY_SERVICE_STATUS = 29,
    ims_MsgId_REQUEST_SET_SERVICE_STATUS = 30,
    ims_MsgId_REQUEST_SUPP_SVC_STATUS = 31,
    ims_MsgId_REQUEST_DEFLECT_CALL = 32,
    ims_MsgId_REQUEST_GET_COLR = 33,
    ims_MsgId_REQUEST_SET_COLR = 34,
    ims_MsgId_REQUEST_QUERY_VT_CALL_QUALITY = 35,
    ims_MsgId_REQUEST_SET_VT_CALL_QUALITY = 36,
    ims_MsgId_REQUEST_HOLD = 37,
    ims_MsgId_REQUEST_RESUME = 38,
    ims_MsgId_REQUEST_SEND_UI_TTY_MODE = 39,
    ims_MsgId_REQUEST_GET_RTP_STATISTICS = 40,
    ims_MsgId_REQUEST_GET_RTP_ERROR_STATISTICS = 41,
    ims_MsgId_REQUEST_GET_WIFI_CALLING_STATUS = 42,
    ims_MsgId_REQUEST_SET_WIFI_CALLING_STATUS = 43,
    ims_MsgId_REQUEST_SET_IMS_CONFIG = 44,
    ims_MsgId_REQUEST_GET_IMS_CONFIG = 45,
    ims_MsgId_REQUEST_SEND_GEOLOCATION_INFO = 46,
    ims_MsgId_REQUEST_GET_VOWIFI_CALL_QUALITY = 47,
    ims_MsgId_REQUEST_GET_VOPS_INFO = 48,
    ims_MsgId_REQUEST_GET_SSAC_INFO = 49,
    ims_MsgId_REQUEST_SET_VOLTE_PREF = 50,
    ims_MsgId_REQUEST_GET_VOLTE_PREF = 51,
    ims_MsgId_REQUEST_GET_HANDOVER_CONFIG = 52,
    ims_MsgId_REQUEST_SET_HANDOVER_CONFIG = 53,
    ims_MsgId_REQUEST_SET_ROAMING_STATUE = 54,
    ims_MsgId_UNSOL_RSP_BASE = 200,
    ims_MsgId_UNSOL_RESPONSE_CALL_STATE_CHANGED = 201,
    ims_MsgId_UNSOL_CALL_RING = 202,
    ims_MsgId_UNSOL_RINGBACK_TONE = 203,
    ims_MsgId_UNSOL_RESPONSE_IMS_NETWORK_STATE_CHANGED = 204,
    ims_MsgId_UNSOL_ENTER_EMERGENCY_CALLBACK_MODE = 205,
    ims_MsgId_UNSOL_EXIT_EMERGENCY_CALLBACK_MODE = 206,
    ims_MsgId_UNSOL_MODIFY_CALL = 207,
    ims_MsgId_UNSOL_RESPONSE_HANDOVER = 208,
    ims_MsgId_UNSOL_REFRESH_CONF_INFO = 209,
    ims_MsgId_UNSOL_SRV_STATUS_UPDATE = 210,
    ims_MsgId_UNSOL_SUPP_SVC_NOTIFICATION = 211,
    ims_MsgId_UNSOL_TTY_NOTIFICATION = 212,
    ims_MsgId_UNSOL_RADIO_STATE_CHANGED = 213,
    ims_MsgId_UNSOL_MWI = 214,
    ims_MsgId_UNSOL_REFRESH_VICE_INFO = 215,
    ims_MsgId_UNSOL_REQUEST_GEOLOCATION = 216,
    ims_MsgId_UNSOL_VOWIFI_CALL_QUALITY = 217,
    ims_MsgId_UNSOL_VOPS_CHANGED = 218,
    ims_MsgId_UNSOL_SSAC_CHANGED = 219,
    ims_MsgId_UNSOL_PARTICIPANT_STATUS_INFO = 220
} ims_MsgId;
#define _ims_MsgId_MIN ims_MsgId_UNKNOWN_REQ
#define _ims_MsgId_MAX ims_MsgId_UNSOL_PARTICIPANT_STATUS_INFO
#define _ims_MsgId_ARRAYSIZE ((ims_MsgId)(ims_MsgId_UNSOL_PARTICIPANT_STATUS_INFO+1))

typedef enum _ims_Error {
    ims_Error_E_SUCCESS = 0,
    ims_Error_E_RADIO_NOT_AVAILABLE = 1,
    ims_Error_E_GENERIC_FAILURE = 2,
    ims_Error_E_REQUEST_NOT_SUPPORTED = 6,
    ims_Error_E_CANCELLED = 7,
    ims_Error_E_UNUSED = 16,
    ims_Error_E_INVALID_PARAMETER = 27,
    ims_Error_E_REJECTED_BY_REMOTE = 28,
    ims_Error_E_IMS_DEREGISTERED = 29,
    ims_Error_E_NETWORK_NOT_SUPPORTED = 30,
    ims_Error_E_HOLD_RESUME_FAILED = 31,
    ims_Error_E_HOLD_RESUME_CANCELED = 32,
    ims_Error_E_REINVITE_COLLISION = 33
} ims_Error;
#define _ims_Error_MIN ims_Error_E_SUCCESS
#define _ims_Error_MAX ims_Error_E_REINVITE_COLLISION
#define _ims_Error_ARRAYSIZE ((ims_Error)(ims_Error_E_REINVITE_COLLISION+1))

typedef enum _ims_CallState {
    ims_CallState_CALL_ACTIVE = 0,
    ims_CallState_CALL_HOLDING = 1,
    ims_CallState_CALL_DIALING = 2,
    ims_CallState_CALL_ALERTING = 3,
    ims_CallState_CALL_INCOMING = 4,
    ims_CallState_CALL_WAITING = 5,
    ims_CallState_CALL_END = 6
} ims_CallState;
#define _ims_CallState_MIN ims_CallState_CALL_ACTIVE
#define _ims_CallState_MAX ims_CallState_CALL_END
#define _ims_CallState_ARRAYSIZE ((ims_CallState)(ims_CallState_CALL_END+1))

typedef enum _ims_RadioState {
    ims_RadioState_RADIO_STATE_OFF = 0,
    ims_RadioState_RADIO_STATE_UNAVAILABLE = 1,
    ims_RadioState_RADIO_STATE_ON = 10
} ims_RadioState;
#define _ims_RadioState_MIN ims_RadioState_RADIO_STATE_OFF
#define _ims_RadioState_MAX ims_RadioState_RADIO_STATE_ON
#define _ims_RadioState_ARRAYSIZE ((ims_RadioState)(ims_RadioState_RADIO_STATE_ON+1))

typedef enum _ims_CallType {
    ims_CallType_CALL_TYPE_VOICE = 0,
    ims_CallType_CALL_TYPE_VT_TX = 1,
    ims_CallType_CALL_TYPE_VT_RX = 2,
    ims_CallType_CALL_TYPE_VT = 3,
    ims_CallType_CALL_TYPE_VT_NODIR = 4,
    ims_CallType_CALL_TYPE_CS_VS_TX = 5,
    ims_CallType_CALL_TYPE_CS_VS_RX = 6,
    ims_CallType_CALL_TYPE_PS_VS_TX = 7,
    ims_CallType_CALL_TYPE_PS_VS_RX = 8,
    ims_CallType_CALL_TYPE_UNKNOWN = 9,
    ims_CallType_CALL_TYPE_SMS = 10,
    ims_CallType_CALL_TYPE_UT = 11
} ims_CallType;
#define _ims_CallType_MIN ims_CallType_CALL_TYPE_VOICE
#define _ims_CallType_MAX ims_CallType_CALL_TYPE_UT
#define _ims_CallType_ARRAYSIZE ((ims_CallType)(ims_CallType_CALL_TYPE_UT+1))

typedef enum _ims_CallSubstate {
    ims_CallSubstate_CALL_SUBSTATE_NONE = 0,
    ims_CallSubstate_CALL_SUBSTATE_AUDIO_CONNECTED_SUSPENDED = 1,
    ims_CallSubstate_CALL_SUBSTATE_VIDEO_CONNECTED_SUSPENDED = 2,
    ims_CallSubstate_CALL_SUBSTATE_AVP_RETRY = 4,
    ims_CallSubstate_CALL_SUBSTATE_MEDIA_PAUSED = 8
} ims_CallSubstate;
#define _ims_CallSubstate_MIN ims_CallSubstate_CALL_SUBSTATE_NONE
#define _ims_CallSubstate_MAX ims_CallSubstate_CALL_SUBSTATE_MEDIA_PAUSED
#define _ims_CallSubstate_ARRAYSIZE ((ims_CallSubstate)(ims_CallSubstate_CALL_SUBSTATE_MEDIA_PAUSED+1))

typedef enum _ims_CallFailCause {
    ims_CallFailCause_CALL_FAIL_UNOBTAINABLE_NUMBER = 1,
    ims_CallFailCause_CALL_FAIL_NORMAL = 16,
    ims_CallFailCause_CALL_FAIL_BUSY = 17,
    ims_CallFailCause_CALL_FAIL_NORMAL_UNSPECIFIED = 31,
    ims_CallFailCause_CALL_FAIL_CONGESTION = 34,
    ims_CallFailCause_CALL_FAIL_INCOMPATIBILITY_DESTINATION = 88,
    ims_CallFailCause_CALL_FAIL_CALL_BARRED = 240,
    ims_CallFailCause_CALL_FAIL_FDN_BLOCKED = 241,
    ims_CallFailCause_CALL_FAIL_EMERGENCY_TEMP_FAILURE = 325,
    ims_CallFailCause_CALL_FAIL_EMERGENCY_PERM_FAILURE = 326,
    ims_CallFailCause_CALL_FAIL_HO_NOT_FEASIBLE = 382,
    ims_CallFailCause_CALL_FAIL_USER_BUSY = 501,
    ims_CallFailCause_CALL_FAIL_USER_REJECT = 502,
    ims_CallFailCause_CALL_FAIL_LOW_BATTERY = 503,
    ims_CallFailCause_CALL_FAIL_BLACKLISTED_CALL_ID = 504,
    ims_CallFailCause_CALL_FAIL_CS_RETRY_REQUIRED = 505,
    ims_CallFailCause_CALL_FAIL_NETWORK_UNAVAILABLE = 1010,
    ims_CallFailCause_CALL_FAIL_FEATURE_UNAVAILABLE = 1011,
    ims_CallFailCause_CALL_FAIL_SIP_Error = 1012,
    ims_CallFailCause_CALL_FAIL_MISC = 1013,
    ims_CallFailCause_CALL_FAIL_ANSWERED_ELSEWHERE = 1014,
    ims_CallFailCause_CALL_FAIL_PULL_OUT_OF_SYNC = 1015,
    ims_CallFailCause_CALL_FAIL_CAUSE_CALL_PULLED = 1016,
    ims_CallFailCause_CALL_FAIL_SIP_REDIRECTED = 2001,
    ims_CallFailCause_CALL_FAIL_SIP_BAD_REQUEST = 2002,
    ims_CallFailCause_CALL_FAIL_SIP_FORBIDDEN = 2003,
    ims_CallFailCause_CALL_FAIL_SIP_NOT_FOUND = 2004,
    ims_CallFailCause_CALL_FAIL_SIP_NOT_SUPPORTED = 2005,
    ims_CallFailCause_CALL_FAIL_SIP_REQUEST_TIMEOUT = 2006,
    ims_CallFailCause_CALL_FAIL_SIP_TEMPORARILY_UNAVAILABLE = 2007,
    ims_CallFailCause_CALL_FAIL_SIP_BAD_ADDRESS = 2008,
    ims_CallFailCause_CALL_FAIL_SIP_BUSY = 2009,
    ims_CallFailCause_CALL_FAIL_SIP_REQUEST_CANCELLED = 2010,
    ims_CallFailCause_CALL_FAIL_SIP_NOT_ACCEPTABLE = 2011,
    ims_CallFailCause_CALL_FAIL_SIP_NOT_REACHABLE = 2012,
    ims_CallFailCause_CALL_FAIL_SIP_SERVER_INTERNAL_ERROR = 2013,
    ims_CallFailCause_CALL_FAIL_SIP_SERVER_NOT_IMPLEMENTED = 2014,
    ims_CallFailCause_CALL_FAIL_SIP_SERVER_BAD_GATEWAY = 2015,
    ims_CallFailCause_CALL_FAIL_SIP_SERVICE_UNAVAILABLE = 2016,
    ims_CallFailCause_CALL_FAIL_SIP_SERVER_TIMEOUT = 2017,
    ims_CallFailCause_CALL_FAIL_SIP_SERVER_VERSION_UNSUPPORTED = 2018,
    ims_CallFailCause_CALL_FAIL_SIP_SERVER_MESSAGE_TOOLARGE = 2019,
    ims_CallFailCause_CALL_FAIL_SIP_SERVER_PRECONDITION_FAILURE = 2020,
    ims_CallFailCause_CALL_FAIL_SIP_USER_REJECTED = 2021,
    ims_CallFailCause_CALL_FAIL_SIP_GLOBAL_ERROR = 2022,
    ims_CallFailCause_CALL_FAIL_MEDIA_INIT_FAILED = 3001,
    ims_CallFailCause_CALL_FAIL_MEDIA_NO_DATA = 3002,
    ims_CallFailCause_CALL_FAIL_MEDIA_NOT_ACCEPTABLE = 3003,
    ims_CallFailCause_CALL_FAIL_MEDIA_UNSPECIFIED_ERROR = 3004,
    ims_CallFailCause_CALL_FAIL_HOLD_RESUME_FAILED = 3005,
    ims_CallFailCause_CALL_FAIL_HOLD_RESUME_CANCELED = 3006,
    ims_CallFailCause_CALL_FAIL_HOLD_REINVITE_COLLISION = 3007,
    ims_CallFailCause_CALL_FAIL_ERROR_UNSPECIFIED = 65535
} ims_CallFailCause;
#define _ims_CallFailCause_MIN ims_CallFailCause_CALL_FAIL_UNOBTAINABLE_NUMBER
#define _ims_CallFailCause_MAX ims_CallFailCause_CALL_FAIL_ERROR_UNSPECIFIED
#define _ims_CallFailCause_ARRAYSIZE ((ims_CallFailCause)(ims_CallFailCause_CALL_FAIL_ERROR_UNSPECIFIED+1))

typedef enum _ims_CallDomain {
    ims_CallDomain_CALL_DOMAIN_UNKNOWN = 0,
    ims_CallDomain_CALL_DOMAIN_CS = 1,
    ims_CallDomain_CALL_DOMAIN_PS = 2,
    ims_CallDomain_CALL_DOMAIN_AUTOMATIC = 3,
    ims_CallDomain_CALL_DOMAIN_NOT_SET = 4
} ims_CallDomain;
#define _ims_CallDomain_MIN ims_CallDomain_CALL_DOMAIN_UNKNOWN
#define _ims_CallDomain_MAX ims_CallDomain_CALL_DOMAIN_NOT_SET
#define _ims_CallDomain_ARRAYSIZE ((ims_CallDomain)(ims_CallDomain_CALL_DOMAIN_NOT_SET+1))

typedef enum _ims_SrvType {
    ims_SrvType_SMS = 1,
    ims_SrvType_VOIP = 2,
    ims_SrvType_VT = 3
} ims_SrvType;
#define _ims_SrvType_MIN ims_SrvType_SMS
#define _ims_SrvType_MAX ims_SrvType_VT
#define _ims_SrvType_ARRAYSIZE ((ims_SrvType)(ims_SrvType_VT+1))

typedef enum _ims_StatusType {
    ims_StatusType_STATUS_DISABLED = 0,
    ims_StatusType_STATUS_PARTIALLY_ENABLED = 1,
    ims_StatusType_STATUS_ENABLED = 2,
    ims_StatusType_STATUS_NOT_SUPPORTED = 3
} ims_StatusType;
#define _ims_StatusType_MIN ims_StatusType_STATUS_DISABLED
#define _ims_StatusType_MAX ims_StatusType_STATUS_NOT_SUPPORTED
#define _ims_StatusType_ARRAYSIZE ((ims_StatusType)(ims_StatusType_STATUS_NOT_SUPPORTED+1))

typedef enum _ims_RadioTechType {
    ims_RadioTechType_RADIO_TECH_ANY = -1,
    ims_RadioTechType_RADIO_TECH_UNKNOWN = 0,
    ims_RadioTechType_RADIO_TECH_GPRS = 1,
    ims_RadioTechType_RADIO_TECH_EDGE = 2,
    ims_RadioTechType_RADIO_TECH_UMTS = 3,
    ims_RadioTechType_RADIO_TECH_IS95A = 4,
    ims_RadioTechType_RADIO_TECH_IS95B = 5,
    ims_RadioTechType_RADIO_TECH_1xRTT = 6,
    ims_RadioTechType_RADIO_TECH_EVDO_0 = 7,
    ims_RadioTechType_RADIO_TECH_EVDO_A = 8,
    ims_RadioTechType_RADIO_TECH_HSDPA = 9,
    ims_RadioTechType_RADIO_TECH_HSUPA = 10,
    ims_RadioTechType_RADIO_TECH_HSPA = 11,
    ims_RadioTechType_RADIO_TECH_EVDO_B = 12,
    ims_RadioTechType_RADIO_TECH_EHRPD = 13,
    ims_RadioTechType_RADIO_TECH_LTE = 14,
    ims_RadioTechType_RADIO_TECH_HSPAP = 15,
    ims_RadioTechType_RADIO_TECH_GSM = 16,
    ims_RadioTechType_RADIO_TECH_TD_SCDMA = 17,
    ims_RadioTechType_RADIO_TECH_WIFI = 18,
    ims_RadioTechType_RADIO_TECH_IWLAN = 19
} ims_RadioTechType;
#define _ims_RadioTechType_MIN ims_RadioTechType_RADIO_TECH_ANY
#define _ims_RadioTechType_MAX ims_RadioTechType_RADIO_TECH_IWLAN
#define _ims_RadioTechType_ARRAYSIZE ((ims_RadioTechType)(ims_RadioTechType_RADIO_TECH_IWLAN+1))

typedef enum _ims_CauseCodes {
    ims_CauseCodes_CAUSE_CODE_UNSPECIFIED = 0,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_UPGRADE_LOCAL_REQ = 1,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_UPGRADE_REMOTE_REQ = 2,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_LOCAL_REQ = 3,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_REMOTE_REQ = 4,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_RTP_TIMEOUT = 5,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_QOS = 6,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_PACKET_LOSS = 7,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_LOW_THRPUT = 8,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_THERM_MITIGATION = 9,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_LIPSYNC = 10,
    ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_GENERIC_ERROR = 11
} ims_CauseCodes;
#define _ims_CauseCodes_MIN ims_CauseCodes_CAUSE_CODE_UNSPECIFIED
#define _ims_CauseCodes_MAX ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_GENERIC_ERROR
#define _ims_CauseCodes_ARRAYSIZE ((ims_CauseCodes)(ims_CauseCodes_CAUSE_CODE_SESSION_MODIFY_DOWNGRADE_GENERIC_ERROR+1))

typedef enum _ims_IpPresentation {
    ims_IpPresentation_IP_PRESENTATION_NUM_ALLOWED = 0,
    ims_IpPresentation_IP_PRESENTATION_NUM_RESTRICTED = 1,
    ims_IpPresentation_IP_PRESENTATION_NUM_DEFAULT = 2
} ims_IpPresentation;
#define _ims_IpPresentation_MIN ims_IpPresentation_IP_PRESENTATION_NUM_ALLOWED
#define _ims_IpPresentation_MAX ims_IpPresentation_IP_PRESENTATION_NUM_DEFAULT
#define _ims_IpPresentation_ARRAYSIZE ((ims_IpPresentation)(ims_IpPresentation_IP_PRESENTATION_NUM_DEFAULT+1))

typedef enum _ims_Handover_Msg_Type {
    ims_Handover_Msg_Type_START = 0,
    ims_Handover_Msg_Type_COMPLETE_SUCCESS = 1,
    ims_Handover_Msg_Type_COMPLETE_FAIL = 2,
    ims_Handover_Msg_Type_CANCEL = 3,
    ims_Handover_Msg_Type_NOT_TRIGGERED = 4
} ims_Handover_Msg_Type;
#define _ims_Handover_Msg_Type_MIN ims_Handover_Msg_Type_START
#define _ims_Handover_Msg_Type_MAX ims_Handover_Msg_Type_NOT_TRIGGERED
#define _ims_Handover_Msg_Type_ARRAYSIZE ((ims_Handover_Msg_Type)(ims_Handover_Msg_Type_NOT_TRIGGERED+1))

typedef enum _ims_Extra_Type {
    ims_Extra_Type_LTE_TO_IWLAN_HO_FAIL = 1
} ims_Extra_Type;
#define _ims_Extra_Type_MIN ims_Extra_Type_LTE_TO_IWLAN_HO_FAIL
#define _ims_Extra_Type_MAX ims_Extra_Type_LTE_TO_IWLAN_HO_FAIL
#define _ims_Extra_Type_ARRAYSIZE ((ims_Extra_Type)(ims_Extra_Type_LTE_TO_IWLAN_HO_FAIL+1))

typedef enum _ims_Tty_Mode_Type {
    ims_Tty_Mode_Type_TTY_MODE_OFF = 0,
    ims_Tty_Mode_Type_TTY_MODE_FULL = 1,
    ims_Tty_Mode_Type_TTY_MODE_HCO = 2,
    ims_Tty_Mode_Type_TTY_MODE_VCO = 3
} ims_Tty_Mode_Type;
#define _ims_Tty_Mode_Type_MIN ims_Tty_Mode_Type_TTY_MODE_OFF
#define _ims_Tty_Mode_Type_MAX ims_Tty_Mode_Type_TTY_MODE_VCO
#define _ims_Tty_Mode_Type_ARRAYSIZE ((ims_Tty_Mode_Type)(ims_Tty_Mode_Type_TTY_MODE_VCO+1))

typedef enum _ims_ClipStatus {
    ims_ClipStatus_NOT_PROVISIONED = 0,
    ims_ClipStatus_PROVISIONED = 1,
    ims_ClipStatus_STATUS_UNKNOWN = 2
} ims_ClipStatus;
#define _ims_ClipStatus_MIN ims_ClipStatus_NOT_PROVISIONED
#define _ims_ClipStatus_MAX ims_ClipStatus_STATUS_UNKNOWN
#define _ims_ClipStatus_ARRAYSIZE ((ims_ClipStatus)(ims_ClipStatus_STATUS_UNKNOWN+1))

typedef enum _ims_ServiceClassStatus {
    ims_ServiceClassStatus_DISABLED = 0,
    ims_ServiceClassStatus_ENABLED = 1
} ims_ServiceClassStatus;
#define _ims_ServiceClassStatus_MIN ims_ServiceClassStatus_DISABLED
#define _ims_ServiceClassStatus_MAX ims_ServiceClassStatus_ENABLED
#define _ims_ServiceClassStatus_ARRAYSIZE ((ims_ServiceClassStatus)(ims_ServiceClassStatus_ENABLED+1))

typedef enum _ims_ConfCallState {
    ims_ConfCallState_RINGING = 0,
    ims_ConfCallState_FOREGROUND = 1,
    ims_ConfCallState_BACKGROUND = 2
} ims_ConfCallState;
#define _ims_ConfCallState_MIN ims_ConfCallState_RINGING
#define _ims_ConfCallState_MAX ims_ConfCallState_BACKGROUND
#define _ims_ConfCallState_ARRAYSIZE ((ims_ConfCallState)(ims_ConfCallState_BACKGROUND+1))

typedef enum _ims_NotificationType {
    ims_NotificationType_MO = 0,
    ims_NotificationType_MT = 1
} ims_NotificationType;
#define _ims_NotificationType_MIN ims_NotificationType_MO
#define _ims_NotificationType_MAX ims_NotificationType_MT
#define _ims_NotificationType_ARRAYSIZE ((ims_NotificationType)(ims_NotificationType_MT+1))

typedef enum _ims_SuppSvcOperationType {
    ims_SuppSvcOperationType_ACTIVATE = 1,
    ims_SuppSvcOperationType_DEACTIVATE = 2,
    ims_SuppSvcOperationType_QUERY = 3,
    ims_SuppSvcOperationType_REGISTER = 4,
    ims_SuppSvcOperationType_ERASURE = 5
} ims_SuppSvcOperationType;
#define _ims_SuppSvcOperationType_MIN ims_SuppSvcOperationType_ACTIVATE
#define _ims_SuppSvcOperationType_MAX ims_SuppSvcOperationType_ERASURE
#define _ims_SuppSvcOperationType_ARRAYSIZE ((ims_SuppSvcOperationType)(ims_SuppSvcOperationType_ERASURE+1))

typedef enum _ims_SuppSvcFacilityType {
    ims_SuppSvcFacilityType_FACILITY_CLIP = 1,
    ims_SuppSvcFacilityType_FACILITY_COLP = 2,
    ims_SuppSvcFacilityType_FACILITY_BAOC = 3,
    ims_SuppSvcFacilityType_FACILITY_BAOIC = 4,
    ims_SuppSvcFacilityType_FACILITY_BAOICxH = 5,
    ims_SuppSvcFacilityType_FACILITY_BAIC = 6,
    ims_SuppSvcFacilityType_FACILITY_BAICr = 7,
    ims_SuppSvcFacilityType_FACILITY_BA_ALL = 8,
    ims_SuppSvcFacilityType_FACILITY_BA_MO = 9,
    ims_SuppSvcFacilityType_FACILITY_BA_MT = 10,
    ims_SuppSvcFacilityType_FACILITY_BS_MT = 11,
    ims_SuppSvcFacilityType_FACILITY_BAICa = 12
} ims_SuppSvcFacilityType;
#define _ims_SuppSvcFacilityType_MIN ims_SuppSvcFacilityType_FACILITY_CLIP
#define _ims_SuppSvcFacilityType_MAX ims_SuppSvcFacilityType_FACILITY_BAICa
#define _ims_SuppSvcFacilityType_ARRAYSIZE ((ims_SuppSvcFacilityType)(ims_SuppSvcFacilityType_FACILITY_BAICa+1))

typedef enum _ims_Quality {
    ims_Quality_LOW = 0,
    ims_Quality_HIGH = 1
} ims_Quality;
#define _ims_Quality_MIN ims_Quality_LOW
#define _ims_Quality_MAX ims_Quality_HIGH
#define _ims_Quality_ARRAYSIZE ((ims_Quality)(ims_Quality_HIGH+1))

typedef enum _ims_MwiMessageType {
    ims_MwiMessageType_MWI_MSG_NONE = -1,
    ims_MwiMessageType_MWI_MSG_VOICE = 0,
    ims_MwiMessageType_MWI_MSG_VIDEO = 1,
    ims_MwiMessageType_MWI_MSG_FAX = 2,
    ims_MwiMessageType_MWI_MSG_PAGER = 3,
    ims_MwiMessageType_MWI_MSG_MULTIMEDIA = 4,
    ims_MwiMessageType_MWI_MSG_TEXT = 5
} ims_MwiMessageType;
#define _ims_MwiMessageType_MIN ims_MwiMessageType_MWI_MSG_NONE
#define _ims_MwiMessageType_MAX ims_MwiMessageType_MWI_MSG_TEXT
#define _ims_MwiMessageType_ARRAYSIZE ((ims_MwiMessageType)(ims_MwiMessageType_MWI_MSG_TEXT+1))

typedef enum _ims_MwiPriority {
    ims_MwiPriority_MWI_MSG_PRIORITY_UNKNOWN = -1,
    ims_MwiPriority_MWI_MSG_PRIORITY_LOW = 0,
    ims_MwiPriority_MWI_MSG_PRIORITY_NORMAL = 1,
    ims_MwiPriority_MWI_MSG_PRIORITY_URGENT = 2
} ims_MwiPriority;
#define _ims_MwiPriority_MIN ims_MwiPriority_MWI_MSG_PRIORITY_UNKNOWN
#define _ims_MwiPriority_MAX ims_MwiPriority_MWI_MSG_PRIORITY_URGENT
#define _ims_MwiPriority_ARRAYSIZE ((ims_MwiPriority)(ims_MwiPriority_MWI_MSG_PRIORITY_URGENT+1))

typedef enum _ims_WifiCallingStatus {
    ims_WifiCallingStatus_WIFI_NOT_SUPPORTED = 0,
    ims_WifiCallingStatus_WIFI_STATUS_ON = 1,
    ims_WifiCallingStatus_WIFI_STATUS_OFF = 2
} ims_WifiCallingStatus;
#define _ims_WifiCallingStatus_MIN ims_WifiCallingStatus_WIFI_NOT_SUPPORTED
#define _ims_WifiCallingStatus_MAX ims_WifiCallingStatus_WIFI_STATUS_OFF
#define _ims_WifiCallingStatus_ARRAYSIZE ((ims_WifiCallingStatus)(ims_WifiCallingStatus_WIFI_STATUS_OFF+1))

typedef enum _ims_WifiCallingPreference {
    ims_WifiCallingPreference_WIFI_PREF_NONE = 0,
    ims_WifiCallingPreference_WIFI_PREFERRED = 1,
    ims_WifiCallingPreference_WIFI_ONLY = 2,
    ims_WifiCallingPreference_CELLULAR_PREFERRED = 3,
    ims_WifiCallingPreference_CELLULAR_ONLY = 4
} ims_WifiCallingPreference;
#define _ims_WifiCallingPreference_MIN ims_WifiCallingPreference_WIFI_PREF_NONE
#define _ims_WifiCallingPreference_MAX ims_WifiCallingPreference_CELLULAR_ONLY
#define _ims_WifiCallingPreference_ARRAYSIZE ((ims_WifiCallingPreference)(ims_WifiCallingPreference_CELLULAR_ONLY+1))

typedef enum _ims_ConfigFailureCause {
    ims_ConfigFailureCause_CONFIG_NO_ERR = 0,
    ims_ConfigFailureCause_CONFIG_IMS_NOT_READY = 1,
    ims_ConfigFailureCause_CONFIG_FILE_NOT_AVAILABLE = 2,
    ims_ConfigFailureCause_CONFIG_READ_FAILED = 3,
    ims_ConfigFailureCause_CONFIG_WRITE_FAILED = 4,
    ims_ConfigFailureCause_CONFIG_OTHER_INTERNAL_ERR = 5
} ims_ConfigFailureCause;
#define _ims_ConfigFailureCause_MIN ims_ConfigFailureCause_CONFIG_NO_ERR
#define _ims_ConfigFailureCause_MAX ims_ConfigFailureCause_CONFIG_OTHER_INTERNAL_ERR
#define _ims_ConfigFailureCause_ARRAYSIZE ((ims_ConfigFailureCause)(ims_ConfigFailureCause_CONFIG_OTHER_INTERNAL_ERR+1))

typedef enum _ims_ConfigItem {
    ims_ConfigItem_CONFIG_ITEM_NONE = 0,
    ims_ConfigItem_CONFIG_ITEM_VOCODER_AMRMODESET = 1,
    ims_ConfigItem_CONFIG_ITEM_VOCODER_AMRWBMODESET = 2,
    ims_ConfigItem_CONFIG_ITEM_SIP_SESSION_TIMER = 3,
    ims_ConfigItem_CONFIG_ITEM_MIN_SESSION_EXPIRY = 4,
    ims_ConfigItem_CONFIG_ITEM_CANCELLATION_TIMER = 5,
    ims_ConfigItem_CONFIG_ITEM_T_DELAY = 6,
    ims_ConfigItem_CONFIG_ITEM_SILENT_REDIAL_ENABLE = 7,
    ims_ConfigItem_CONFIG_ITEM_SIP_T1_TIMER = 8,
    ims_ConfigItem_CONFIG_ITEM_SIP_T2_TIMER = 9,
    ims_ConfigItem_CONFIG_ITEM_SIP_TF_TIMER = 10,
    ims_ConfigItem_CONFIG_ITEM_VLT_SETTING_ENABLED = 11,
    ims_ConfigItem_CONFIG_ITEM_LVC_SETTING_ENABLED = 12,
    ims_ConfigItem_CONFIG_ITEM_DOMAIN_NAME = 13,
    ims_ConfigItem_CONFIG_ITEM_SMS_FORMAT = 14,
    ims_ConfigItem_CONFIG_ITEM_SMS_OVER_IP = 15,
    ims_ConfigItem_CONFIG_ITEM_PUBLISH_TIMER = 16,
    ims_ConfigItem_CONFIG_ITEM_PUBLISH_TIMER_EXTENDED = 17,
    ims_ConfigItem_CONFIG_ITEM_CAPABILITIES_CACHE_EXPIRATION = 18,
    ims_ConfigItem_CONFIG_ITEM_AVAILABILITY_CACHE_EXPIRATION = 19,
    ims_ConfigItem_CONFIG_ITEM_CAPABILITIES_POLL_INTERVAL = 20,
    ims_ConfigItem_CONFIG_ITEM_SOURCE_THROTTLE_PUBLISH = 21,
    ims_ConfigItem_CONFIG_ITEM_MAX_NUM_ENTRIES_IN_RCL = 22,
    ims_ConfigItem_CONFIG_ITEM_CAPAB_POLL_LIST_SUB_EXP = 23,
    ims_ConfigItem_CONFIG_ITEM_GZIP_FLAG = 24,
    ims_ConfigItem_CONFIG_ITEM_EAB_SETTING_ENABLED = 25,
    ims_ConfigItem_CONFIG_ITEM_MOBILE_DATA_ENABLED = 26,
    ims_ConfigItem_CONFIG_ITEM_VOICE_OVER_WIFI_ENABLED = 27,
    ims_ConfigItem_CONFIG_ITEM_VOICE_OVER_WIFI_ROAMING = 28,
    ims_ConfigItem_CONFIG_ITEM_VOICE_OVER_WIFI_MODE = 29,
    ims_ConfigItem_CONFIG_ITEM_CAPABILITY_DISCOVERY_ENABLED = 30,
    ims_ConfigItem_CONFIG_ITEM_EMERGENCY_CALL_TIMER = 31,
    ims_ConfigItem_CONFIG_ITEM_SSAC_HYSTERESIS_TIMER = 32,
    ims_ConfigItem_CONFIG_ITEM_VOLTE_USER_OPT_IN_STATUS = 33,
    ims_ConfigItem_CONFIG_ITEM_LBO_PCSCF_ADDRESS = 34,
    ims_ConfigItem_CONFIG_ITEM_KEEP_ALIVE_ENABLED = 35,
    ims_ConfigItem_CONFIG_ITEM_REGISTRATION_RETRY_BASE_TIME_SEC = 36,
    ims_ConfigItem_CONFIG_ITEM_REGISTRATION_RETRY_MAX_TIME_SEC = 37,
    ims_ConfigItem_CONFIG_ITEM_SPEECH_START_PORT = 38,
    ims_ConfigItem_CONFIG_ITEM_SPEECH_END_PORT = 39,
    ims_ConfigItem_CONFIG_ITEM_SIP_INVITE_REQ_RETX_INTERVAL_MSEC = 40,
    ims_ConfigItem_CONFIG_ITEM_SIP_INVITE_RSP_WAIT_TIME_MSEC = 41,
    ims_ConfigItem_CONFIG_ITEM_SIP_INVITE_RSP_RETX_WAIT_TIME_MSEC = 42,
    ims_ConfigItem_CONFIG_ITEM_SIP_NON_INVITE_REQ_RETX_INTERVAL_MSEC = 43,
    ims_ConfigItem_CONFIG_ITEM_SIP_NON_INVITE_TXN_TIMEOUT_TIMER_MSEC = 44,
    ims_ConfigItem_CONFIG_ITEM_SIP_INVITE_RSP_RETX_INTERVAL_MSEC = 45,
    ims_ConfigItem_CONFIG_ITEM_SIP_ACK_RECEIPT_WAIT_TIME_MSEC = 46,
    ims_ConfigItem_CONFIG_ITEM_SIP_ACK_RETX_WAIT_TIME_MSEC = 47,
    ims_ConfigItem_CONFIG_ITEM_SIP_NON_INVITE_REQ_RETX_WAIT_TIME_MSEC = 48,
    ims_ConfigItem_CONFIG_ITEM_SIP_NON_INVITE_RSP_RETX_WAIT_TIME_MSEC = 49,
    ims_ConfigItem_CONFIG_ITEM_AMR_WB_OCTET_ALIGNED_PT = 50,
    ims_ConfigItem_CONFIG_ITEM_AMR_WB_BANDWIDTH_EFFICIENT_PT = 51,
    ims_ConfigItem_CONFIG_ITEM_AMR_OCTET_ALIGNED_PT = 52,
    ims_ConfigItem_CONFIG_ITEM_AMR_BANDWIDTH_EFFICIENT_PT = 53,
    ims_ConfigItem_CONFIG_ITEM_DTMF_WB_PT = 54,
    ims_ConfigItem_CONFIG_ITEM_DTMF_NB_PT = 55,
    ims_ConfigItem_CONFIG_ITEM_AMR_DEFAULT_MODE = 56,
    ims_ConfigItem_CONFIG_ITEM_SMS_PSI = 57,
    ims_ConfigItem_CONFIG_ITEM_VIDEO_QUALITY = 58,
    ims_ConfigItem_CONFIG_ITEM_THRESHOLD_LTE1 = 59,
    ims_ConfigItem_CONFIG_ITEM_THRESHOLD_LTE2 = 60,
    ims_ConfigItem_CONFIG_ITEM_THRESHOLD_LTE3 = 61,
    ims_ConfigItem_CONFIG_ITEM_THRESHOLD_1x = 62,
    ims_ConfigItem_CONFIG_ITEM_THRESHOLD_WIFI_A = 63,
    ims_ConfigItem_CONFIG_ITEM_THRESHOLD_WIFI_B = 64,
    ims_ConfigItem_CONFIG_ITEM_T_EPDG_LTE = 65,
    ims_ConfigItem_CONFIG_ITEM_T_EPDG_WIFI = 66,
    ims_ConfigItem_CONFIG_ITEM_T_EPDG_1x = 67,
    ims_ConfigItem_CONFIG_ITEM_VWF_SETTING_ENABLED = 68,
    ims_ConfigItem_CONFIG_ITEM_VCE_SETTING_ENABLED = 69
} ims_ConfigItem;
#define _ims_ConfigItem_MIN ims_ConfigItem_CONFIG_ITEM_NONE
#define _ims_ConfigItem_MAX ims_ConfigItem_CONFIG_ITEM_VCE_SETTING_ENABLED
#define _ims_ConfigItem_ARRAYSIZE ((ims_ConfigItem)(ims_ConfigItem_CONFIG_ITEM_VCE_SETTING_ENABLED+1))

typedef enum _ims_EctType {
    ims_EctType_BLIND_TRANSFER = 0,
    ims_EctType_ASSURED_TRANSFER = 1,
    ims_EctType_CONSULTATIVE_TRANSFER = 2
} ims_EctType;
#define _ims_EctType_MIN ims_EctType_BLIND_TRANSFER
#define _ims_EctType_MAX ims_EctType_CONSULTATIVE_TRANSFER
#define _ims_EctType_ARRAYSIZE ((ims_EctType)(ims_EctType_CONSULTATIVE_TRANSFER+1))

typedef enum _ims_voWiFiQuality {
    ims_voWiFiQuality_VOWIFI_QUALITY_NONE = 0,
    ims_voWiFiQuality_VOWIFI_QUALITY_EXCELLENT = 1,
    ims_voWiFiQuality_VOWIFI_QUALITY_FAIR = 2,
    ims_voWiFiQuality_VOWIFI_QUALITY_BAD = 4
} ims_voWiFiQuality;
#define _ims_voWiFiQuality_MIN ims_voWiFiQuality_VOWIFI_QUALITY_NONE
#define _ims_voWiFiQuality_MAX ims_voWiFiQuality_VOWIFI_QUALITY_BAD
#define _ims_voWiFiQuality_ARRAYSIZE ((ims_voWiFiQuality)(ims_voWiFiQuality_VOWIFI_QUALITY_BAD+1))

typedef enum _ims_ConfParticipantOperation {
    ims_ConfParticipantOperation_ADD = 0,
    ims_ConfParticipantOperation_REMOVE = 1
} ims_ConfParticipantOperation;
#define _ims_ConfParticipantOperation_MIN ims_ConfParticipantOperation_ADD
#define _ims_ConfParticipantOperation_MAX ims_ConfParticipantOperation_REMOVE
#define _ims_ConfParticipantOperation_ARRAYSIZE ((ims_ConfParticipantOperation)(ims_ConfParticipantOperation_REMOVE+1))

typedef enum _ims_VoltePref {
    ims_VoltePref_VOLTE_PREF_DISABLED = 0,
    ims_VoltePref_VOLTE_PREF_ENABLED = 1,
    ims_VoltePref_VOLTE_PREF_UNKNOWN = 2
} ims_VoltePref;
#define _ims_VoltePref_MIN ims_VoltePref_VOLTE_PREF_DISABLED
#define _ims_VoltePref_MAX ims_VoltePref_VOLTE_PREF_UNKNOWN
#define _ims_VoltePref_ARRAYSIZE ((ims_VoltePref)(ims_VoltePref_VOLTE_PREF_UNKNOWN+1))

typedef enum _ims_HandoverConfig {
    ims_HandoverConfig_HO_ENABLED_ALL = 1,
    ims_HandoverConfig_HO_DISABLED_ALL = 2,
    ims_HandoverConfig_HO_ENABLED_WLAN_TO_WWAN_ONLY = 3,
    ims_HandoverConfig_HO_ENABLED_WWAN_TO_WLAN_ONLY = 4
} ims_HandoverConfig;
#define _ims_HandoverConfig_MIN ims_HandoverConfig_HO_ENABLED_ALL
#define _ims_HandoverConfig_MAX ims_HandoverConfig_HO_ENABLED_WWAN_TO_WLAN_ONLY
#define _ims_HandoverConfig_ARRAYSIZE ((ims_HandoverConfig)(ims_HandoverConfig_HO_ENABLED_WWAN_TO_WLAN_ONLY+1))

typedef enum _ims_Registration_RegState {
    ims_Registration_RegState_REGISTERED = 1,
    ims_Registration_RegState_NOT_REGISTERED = 2,
    ims_Registration_RegState_REGISTERING = 3
} ims_Registration_RegState;
#define _ims_Registration_RegState_MIN ims_Registration_RegState_REGISTERED
#define _ims_Registration_RegState_MAX ims_Registration_RegState_REGISTERING
#define _ims_Registration_RegState_ARRAYSIZE ((ims_Registration_RegState)(ims_Registration_RegState_REGISTERING+1))

typedef enum _ims_RingBackTone_ToneFlag {
    ims_RingBackTone_ToneFlag_STOP = 0,
    ims_RingBackTone_ToneFlag_START = 1
} ims_RingBackTone_ToneFlag;
#define _ims_RingBackTone_ToneFlag_MIN ims_RingBackTone_ToneFlag_STOP
#define _ims_RingBackTone_ToneFlag_MAX ims_RingBackTone_ToneFlag_START
#define _ims_RingBackTone_ToneFlag_ARRAYSIZE ((ims_RingBackTone_ToneFlag)(ims_RingBackTone_ToneFlag_START+1))

typedef enum _ims_IFConnected_Version {
    ims_IFConnected_Version_VERSION_0 = 0
} ims_IFConnected_Version;
#define _ims_IFConnected_Version_MIN ims_IFConnected_Version_VERSION_0
#define _ims_IFConnected_Version_MAX ims_IFConnected_Version_VERSION_0
#define _ims_IFConnected_Version_ARRAYSIZE ((ims_IFConnected_Version)(ims_IFConnected_Version_VERSION_0+1))

/* Struct definitions */
typedef struct _ims_AddressInfo {
    pb_callback_t city;
    pb_callback_t state;
    pb_callback_t country;
    pb_callback_t postalCode;
    pb_callback_t countryCode;
/* @@protoc_insertion_point(struct:ims_AddressInfo) */
} ims_AddressInfo;

typedef struct _ims_CallList {
    pb_callback_t callAttributes;
/* @@protoc_insertion_point(struct:ims_CallList) */
} ims_CallList;

typedef struct _ims_Dtmf {
    pb_callback_t dtmf;
/* @@protoc_insertion_point(struct:ims_Dtmf) */
} ims_Dtmf;

typedef struct _ims_Mwi {
    pb_callback_t mwiMsgSummary;
    pb_callback_t ueAddress;
    pb_callback_t mwiMsgDetail;
/* @@protoc_insertion_point(struct:ims_Mwi) */
} ims_Mwi;

typedef struct _ims_SrvStatusList {
    pb_callback_t SrvStatusInfo;
/* @@protoc_insertion_point(struct:ims_SrvStatusList) */
} ims_SrvStatusList;

typedef struct _ims_ViceInfo {
    pb_callback_t vice_info_uri;
/* @@protoc_insertion_point(struct:ims_ViceInfo) */
} ims_ViceInfo;

typedef struct _ims_Answer {
    bool has_call_type;
    ims_CallType call_type;
    bool has_presentation;
    ims_IpPresentation presentation;
/* @@protoc_insertion_point(struct:ims_Answer) */
} ims_Answer;

typedef struct _ims_CallDetails {
    bool has_callType;
    ims_CallType callType;
    bool has_callDomain;
    ims_CallDomain callDomain;
    bool has_extrasLength;
    uint32_t extrasLength;
    pb_callback_t extras;
    bool has_localAbility;
    ims_SrvStatusList localAbility;
    bool has_peerAbility;
    ims_SrvStatusList peerAbility;
    bool has_callSubstate;
    ims_CallSubstate callSubstate;
    bool has_mediaId;
    int32_t mediaId;
    bool has_causeCode;
    ims_CauseCodes causeCode;
/* @@protoc_insertion_point(struct:ims_CallDetails) */
} ims_CallDetails;

typedef struct _ims_CallFwdTimerInfo {
    bool has_year;
    uint32_t year;
    bool has_month;
    uint32_t month;
    bool has_day;
    uint32_t day;
    bool has_hour;
    uint32_t hour;
    bool has_minute;
    uint32_t minute;
    bool has_second;
    uint32_t second;
    bool has_timezone;
    uint32_t timezone;
/* @@protoc_insertion_point(struct:ims_CallFwdTimerInfo) */
} ims_CallFwdTimerInfo;

typedef struct _ims_CbNumList {
    bool has_status;
    ims_ServiceClassStatus status;
    pb_callback_t number;
/* @@protoc_insertion_point(struct:ims_CbNumList) */
} ims_CbNumList;

typedef struct _ims_Clir {
    bool has_param_m;
    uint32_t param_m;
    bool has_param_n;
    uint32_t param_n;
/* @@protoc_insertion_point(struct:ims_Clir) */
} ims_Clir;

typedef struct _ims_ConfInfo {
    pb_callback_t conf_info_uri;
    bool has_confCallState;
    ims_ConfCallState confCallState;
/* @@protoc_insertion_point(struct:ims_ConfInfo) */
} ims_ConfInfo;

typedef struct _ims_ConfigMsg {
    bool has_item;
    ims_ConfigItem item;
    bool has_boolValue;
    bool boolValue;
    bool has_intValue;
    uint32_t intValue;
    pb_callback_t stringValue;
    bool has_errorCause;
    ims_ConfigFailureCause errorCause;
/* @@protoc_insertion_point(struct:ims_ConfigMsg) */
} ims_ConfigMsg;

typedef struct _ims_DeflectCall {
    bool has_conn_index;
    uint32_t conn_index;
    pb_callback_t number;
/* @@protoc_insertion_point(struct:ims_DeflectCall) */
} ims_DeflectCall;

typedef struct _ims_ExplicitCallTransfer {
    bool has_callId;
    uint32_t callId;
    bool has_ectType;
    ims_EctType ectType;
    pb_callback_t targetAddress;
    bool has_targetCallId;
    uint32_t targetCallId;
/* @@protoc_insertion_point(struct:ims_ExplicitCallTransfer) */
} ims_ExplicitCallTransfer;

typedef struct _ims_Extra {
    bool has_type;
    ims_Extra_Type type;
    pb_callback_t extraInfo;
/* @@protoc_insertion_point(struct:ims_Extra) */
} ims_Extra;

typedef struct _ims_GeoLocationInfo {
    bool has_lat;
    double lat;
    bool has_lon;
    double lon;
    bool has_addressInfo;
    ims_AddressInfo addressInfo;
/* @@protoc_insertion_point(struct:ims_GeoLocationInfo) */
} ims_GeoLocationInfo;

typedef struct _ims_HandoverConfigMsg {
    bool has_hoConfig;
    ims_HandoverConfig hoConfig;
/* @@protoc_insertion_point(struct:ims_HandoverConfigMsg) */
} ims_HandoverConfigMsg;

typedef struct _ims_Hold {
    bool has_callId;
    uint32_t callId;
/* @@protoc_insertion_point(struct:ims_Hold) */
} ims_Hold;

typedef struct _ims_IFConnected {
    bool has_if_version;
    ims_IFConnected_Version if_version;
/* @@protoc_insertion_point(struct:ims_IFConnected) */
} ims_IFConnected;

typedef struct _ims_Info {
    bool has_isValid;
    bool isValid;
    bool has_type;
    ims_SrvType type;
    bool has_callType;
    ims_CallType callType;
    bool has_status;
    ims_StatusType status;
    pb_callback_t userdata;
    bool has_restrictCause;
    uint32_t restrictCause;
    pb_callback_t accTechStatus;
/* @@protoc_insertion_point(struct:ims_Info) */
} ims_Info;

typedef struct _ims_LastFailCause {
    bool has_cause;
    ims_CallFailCause cause;
/* @@protoc_insertion_point(struct:ims_LastFailCause) */
} ims_LastFailCause;

typedef struct _ims_MsgTag {
    uint32_t token;
    ims_MsgType type;
    ims_MsgId id;
    ims_Error error;
/* @@protoc_insertion_point(struct:ims_MsgTag) */
} ims_MsgTag;

typedef struct _ims_Mute {
    bool has_mute_flag;
    bool mute_flag;
/* @@protoc_insertion_point(struct:ims_Mute) */
} ims_Mute;

typedef struct _ims_MwiMessageDetails {
    pb_callback_t toAddress;
    pb_callback_t fromAddress;
    pb_callback_t subject;
    pb_callback_t date;
    bool has_priority;
    ims_MwiPriority priority;
    pb_callback_t messageId;
    bool has_messageType;
    ims_MwiMessageType messageType;
/* @@protoc_insertion_point(struct:ims_MwiMessageDetails) */
} ims_MwiMessageDetails;

typedef struct _ims_MwiMessageSummary {
    bool has_messageType;
    ims_MwiMessageType messageType;
    bool has_newMessage;
    uint32_t newMessage;
    bool has_oldMessage;
    uint32_t oldMessage;
    bool has_newUrgent;
    uint32_t newUrgent;
    bool has_oldUrgent;
    uint32_t oldUrgent;
/* @@protoc_insertion_point(struct:ims_MwiMessageSummary) */
} ims_MwiMessageSummary;

typedef struct _ims_ParticipantStatusInfo {
    bool has_callId;
    uint32_t callId;
    bool has_operation;
    ims_ConfParticipantOperation operation;
    bool has_sipStatus;
    uint32_t sipStatus;
    pb_callback_t participantUri;
    bool has_isEct;
    bool isEct;
/* @@protoc_insertion_point(struct:ims_ParticipantStatusInfo) */
} ims_ParticipantStatusInfo;

typedef struct _ims_RadioStateChanged {
    bool has_state;
    ims_RadioState state;
/* @@protoc_insertion_point(struct:ims_RadioStateChanged) */
} ims_RadioStateChanged;

typedef struct _ims_Registration {
    bool has_state;
    ims_Registration_RegState state;
    bool has_errorCode;
    uint32_t errorCode;
    pb_callback_t errorMessage;
    bool has_radioTech;
    ims_RadioTechType radioTech;
    pb_callback_t pAssociatedUris;
/* @@protoc_insertion_point(struct:ims_Registration) */
} ims_Registration;

typedef struct _ims_Resume {
    bool has_callId;
    uint32_t callId;
/* @@protoc_insertion_point(struct:ims_Resume) */
} ims_Resume;

typedef struct _ims_RingBackTone {
    bool has_flag;
    ims_RingBackTone_ToneFlag flag;
/* @@protoc_insertion_point(struct:ims_RingBackTone) */
} ims_RingBackTone;

typedef struct _ims_RtpStatisticsData {
    bool has_count;
    uint32_t count;
/* @@protoc_insertion_point(struct:ims_RtpStatisticsData) */
} ims_RtpStatisticsData;

typedef struct _ims_ServiceClass {
    bool has_service_Class;
    uint32_t service_Class;
/* @@protoc_insertion_point(struct:ims_ServiceClass) */
} ims_ServiceClass;

typedef struct _ims_SipErrorInfo {
    bool has_sipErrorCode;
    uint32_t sipErrorCode;
    pb_callback_t sipErrorString;
/* @@protoc_insertion_point(struct:ims_SipErrorInfo) */
} ims_SipErrorInfo;

typedef struct _ims_SsacInfo {
    bool has_barringFactorVoice;
    uint32_t barringFactorVoice;
    bool has_barringTimeVoice;
    uint32_t barringTimeVoice;
    bool has_barringFactorVideo;
    uint32_t barringFactorVideo;
    bool has_barringTimeVideo;
    uint32_t barringTimeVideo;
    bool has_barringFactorVoiceSib;
    uint32_t barringFactorVoiceSib;
    bool has_barringTimeVoiceSib;
    uint32_t barringTimeVoiceSib;
    bool has_barringFactorVideoSib;
    uint32_t barringFactorVideoSib;
    bool has_barringTimeVideoSib;
    uint32_t barringTimeVideoSib;
/* @@protoc_insertion_point(struct:ims_SsacInfo) */
} ims_SsacInfo;

typedef struct _ims_SuppSvcNotification {
    bool has_notificationType;
    ims_NotificationType notificationType;
    bool has_code;
    uint32_t code;
    bool has_index;
    uint32_t index;
    bool has_type;
    uint32_t type;
    pb_callback_t number;
    bool has_connId;
    uint32_t connId;
    pb_callback_t history_info;
    bool has_hold_tone;
    bool hold_tone;
/* @@protoc_insertion_point(struct:ims_SuppSvcNotification) */
} ims_SuppSvcNotification;

typedef struct _ims_SuppSvcStatus {
    bool has_status;
    ims_ServiceClassStatus status;
/* @@protoc_insertion_point(struct:ims_SuppSvcStatus) */
} ims_SuppSvcStatus;

typedef struct _ims_SwitchWaitingOrHoldingAndActive {
    bool has_call_type;
    ims_CallType call_type;
/* @@protoc_insertion_point(struct:ims_SwitchWaitingOrHoldingAndActive) */
} ims_SwitchWaitingOrHoldingAndActive;

typedef struct _ims_TtyNotify {
    bool has_mode;
    ims_Tty_Mode_Type mode;
    pb_callback_t userData;
/* @@protoc_insertion_point(struct:ims_TtyNotify) */
} ims_TtyNotify;

typedef struct _ims_VideoCallQuality {
    bool has_quality;
    ims_Quality quality;
/* @@protoc_insertion_point(struct:ims_VideoCallQuality) */
} ims_VideoCallQuality;

typedef struct _ims_VoWiFiCallQuality {
    bool has_quality;
    ims_voWiFiQuality quality;
/* @@protoc_insertion_point(struct:ims_VoWiFiCallQuality) */
} ims_VoWiFiCallQuality;

typedef struct _ims_VolteUserPref {
    bool has_mode;
    ims_VoltePref mode;
/* @@protoc_insertion_point(struct:ims_VolteUserPref) */
} ims_VolteUserPref;

typedef struct _ims_VopsInfo {
    bool has_isVopsEnabled;
    bool isVopsEnabled;
/* @@protoc_insertion_point(struct:ims_VopsInfo) */
} ims_VopsInfo;

typedef struct _ims_WifiCallingInfo {
    bool has_status;
    ims_WifiCallingStatus status;
    bool has_preference;
    ims_WifiCallingPreference preference;
/* @@protoc_insertion_point(struct:ims_WifiCallingInfo) */
} ims_WifiCallingInfo;

typedef struct _ims_CallFailCauseResponse {
    bool has_failcause;
    ims_CallFailCause failcause;
    pb_callback_t errorinfo;
    pb_callback_t networkErrorString;
    bool has_errorDetails;
    ims_SipErrorInfo errorDetails;
/* @@protoc_insertion_point(struct:ims_CallFailCauseResponse) */
} ims_CallFailCauseResponse;

typedef struct _ims_CallForwardInfoList {
    pb_callback_t info;
    bool has_errorDetails;
    ims_SipErrorInfo errorDetails;
/* @@protoc_insertion_point(struct:ims_CallForwardInfoList) */
} ims_CallForwardInfoList;

typedef struct _ims_CallForwardInfoList_CallForwardInfo {
    bool has_status;
    uint32_t status;
    bool has_reason;
    uint32_t reason;
    bool has_service_class;
    uint32_t service_class;
    bool has_toa;
    uint32_t toa;
    pb_callback_t number;
    bool has_time_seconds;
    uint32_t time_seconds;
    bool has_callFwdTimerStart;
    ims_CallFwdTimerInfo callFwdTimerStart;
    bool has_callFwdTimerEnd;
    ims_CallFwdTimerInfo callFwdTimerEnd;
/* @@protoc_insertion_point(struct:ims_CallForwardInfoList_CallForwardInfo) */
} ims_CallForwardInfoList_CallForwardInfo;

typedef struct _ims_CallModify {
    bool has_callIndex;
    uint32_t callIndex;
    bool has_callDetails;
    ims_CallDetails callDetails;
    bool has_error;
    ims_Error error;
/* @@protoc_insertion_point(struct:ims_CallModify) */
} ims_CallModify;

typedef struct _ims_CallWaitingInfo {
    bool has_service_status;
    ims_ServiceClassStatus service_status;
    bool has_service_class;
    ims_ServiceClass service_class;
    bool has_errorDetails;
    ims_SipErrorInfo errorDetails;
/* @@protoc_insertion_point(struct:ims_CallWaitingInfo) */
} ims_CallWaitingInfo;

typedef struct _ims_CbNumListType {
    bool has_serviceClass;
    ims_ServiceClass serviceClass;
    pb_callback_t cb_num_list;
/* @@protoc_insertion_point(struct:ims_CbNumListType) */
} ims_CbNumListType;

typedef struct _ims_ClipProvisionStatus {
    bool has_clip_status;
    ims_ClipStatus clip_status;
    bool has_errorDetails;
    ims_SipErrorInfo errorDetails;
/* @@protoc_insertion_point(struct:ims_ClipProvisionStatus) */
} ims_ClipProvisionStatus;

typedef struct _ims_Colr {
    bool has_presentation;
    ims_IpPresentation presentation;
    bool has_errorDetails;
    ims_SipErrorInfo errorDetails;
/* @@protoc_insertion_point(struct:ims_Colr) */
} ims_Colr;

typedef struct _ims_Dial {
    pb_callback_t address;
    bool has_clir;
    uint32_t clir;
    bool has_callDetails;
    ims_CallDetails callDetails;
    bool has_presentation;
    ims_IpPresentation presentation;
    bool has_isConferenceUri;
    bool isConferenceUri;
    bool has_isCallPull;
    bool isCallPull;
    bool has_isEncrypted;
    bool isEncrypted;
/* @@protoc_insertion_point(struct:ims_Dial) */
} ims_Dial;

typedef struct _ims_Handover {
    bool has_type;
    ims_Handover_Msg_Type type;
    bool has_srcTech;
    ims_RadioTechType srcTech;
    bool has_targetTech;
    ims_RadioTechType targetTech;
    bool has_hoExtra;
    ims_Extra hoExtra;
    pb_callback_t errorCode;
    pb_callback_t errorMessage;
/* @@protoc_insertion_point(struct:ims_Handover) */
} ims_Handover;

typedef struct _ims_StatusForAccessTech {
    bool has_networkMode;
    ims_RadioTechType networkMode;
    bool has_status;
    ims_StatusType status;
    bool has_restrictionCause;
    uint32_t restrictionCause;
    bool has_registered;
    ims_Registration registered;
/* @@protoc_insertion_point(struct:ims_StatusForAccessTech) */
} ims_StatusForAccessTech;

typedef struct _ims_SuppSvcResponse {
    bool has_status;
    ims_ServiceClassStatus status;
    bool has_facilityType;
    uint32_t facilityType;
    pb_callback_t failureCause;
    pb_callback_t cbNumListType;
    bool has_errorDetails;
    ims_SipErrorInfo errorDetails;
/* @@protoc_insertion_point(struct:ims_SuppSvcResponse) */
} ims_SuppSvcResponse;

typedef struct _ims_CallList_Call {
    bool has_state;
    ims_CallState state;
    bool has_index;
    uint32_t index;
    bool has_toa;
    uint32_t toa;
    bool has_isMpty;
    bool isMpty;
    bool has_isMT;
    bool isMT;
    bool has_als;
    uint32_t als;
    bool has_isVoice;
    bool isVoice;
    bool has_isVoicePrivacy;
    bool isVoicePrivacy;
    pb_callback_t number;
    bool has_numberPresentation;
    uint32_t numberPresentation;
    pb_callback_t name;
    bool has_namePresentation;
    uint32_t namePresentation;
    bool has_callDetails;
    ims_CallDetails callDetails;
    bool has_failCause;
    ims_CallFailCauseResponse failCause;
    bool has_isEncrypted;
    bool isEncrypted;
    bool has_isCalledPartyRinging;
    bool isCalledPartyRinging;
    pb_callback_t historyInfo;
/* @@protoc_insertion_point(struct:ims_CallList_Call) */
} ims_CallList_Call;

typedef struct _ims_Hangup {
    bool has_conn_index;
    uint32_t conn_index;
    bool has_multi_party;
    bool multi_party;
    pb_callback_t conn_uri;
    bool has_conf_id;
    uint32_t conf_id;
    bool has_failCauseResponse;
    ims_CallFailCauseResponse failCauseResponse;
/* @@protoc_insertion_point(struct:ims_Hangup) */
} ims_Hangup;

typedef struct _ims_SuppSvcRequest {
    bool has_operationType;
    uint32_t operationType;
    bool has_facilityType;
    uint32_t facilityType;
    bool has_cbNumListType;
    ims_CbNumListType cbNumListType;
/* @@protoc_insertion_point(struct:ims_SuppSvcRequest) */
} ims_SuppSvcRequest;

/* Default values for struct fields */
extern const uint32_t ims_CallDetails_extrasLength_default;
extern const int32_t ims_CallDetails_mediaId_default;

/* Initializer values for message structs */
#define ims_MsgTag_init_default                  {0, (ims_MsgType)0, (ims_MsgId)0, (ims_Error)0}
#define ims_CallFailCauseResponse_init_default   {false, (ims_CallFailCause)0, {{NULL}, NULL}, {{NULL}, NULL}, false, ims_SipErrorInfo_init_default}
#define ims_StatusForAccessTech_init_default     {false, (ims_RadioTechType)0, false, (ims_StatusType)0, false, 0, false, ims_Registration_init_default}
#define ims_Info_init_default                    {false, 0, false, (ims_SrvType)0, false, (ims_CallType)0, false, (ims_StatusType)0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define ims_SrvStatusList_init_default           {{{NULL}, NULL}}
#define ims_CallDetails_init_default             {false, (ims_CallType)0, false, (ims_CallDomain)0, false, 0u, {{NULL}, NULL}, false, ims_SrvStatusList_init_default, false, ims_SrvStatusList_init_default, false, (ims_CallSubstate)0, false, -1, false, (ims_CauseCodes)0}
#define ims_CallModify_init_default              {false, 0, false, ims_CallDetails_init_default, false, (ims_Error)0}
#define ims_CallList_init_default                {{{NULL}, NULL}}
#define ims_CallList_Call_init_default           {false, (ims_CallState)0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, ims_CallDetails_init_default, false, ims_CallFailCauseResponse_init_default, false, 0, false, 0, {{NULL}, NULL}}
#define ims_Colr_init_default                    {false, (ims_IpPresentation)0, false, ims_SipErrorInfo_init_default}
#define ims_Dial_init_default                    {{{NULL}, NULL}, false, 0, false, ims_CallDetails_init_default, false, (ims_IpPresentation)0, false, 0, false, 0, false, 0}
#define ims_Hangup_init_default                  {false, 0, false, 0, {{NULL}, NULL}, false, 0, false, ims_CallFailCauseResponse_init_default}
#define ims_DeflectCall_init_default             {false, 0, {{NULL}, NULL}}
#define ims_Clir_init_default                    {false, 0, false, 0}
#define ims_Answer_init_default                  {false, (ims_CallType)0, false, (ims_IpPresentation)0}
#define ims_SwitchWaitingOrHoldingAndActive_init_default {false, (ims_CallType)0}
#define ims_Mute_init_default                    {false, 0}
#define ims_Dtmf_init_default                    {{{NULL}, NULL}}
#define ims_Registration_init_default            {false, (ims_Registration_RegState)0, false, 0, {{NULL}, NULL}, false, (ims_RadioTechType)0, {{NULL}, NULL}}
#define ims_RingBackTone_init_default            {false, (ims_RingBackTone_ToneFlag)0}
#define ims_IFConnected_init_default             {false, (ims_IFConnected_Version)0}
#define ims_LastFailCause_init_default           {false, (ims_CallFailCause)0}
#define ims_Extra_init_default                   {false, (ims_Extra_Type)0, {{NULL}, NULL}}
#define ims_Handover_init_default                {false, (ims_Handover_Msg_Type)0, false, (ims_RadioTechType)0, false, (ims_RadioTechType)0, false, ims_Extra_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define ims_TtyNotify_init_default               {false, (ims_Tty_Mode_Type)0, {{NULL}, NULL}}
#define ims_RadioStateChanged_init_default       {false, (ims_RadioState)0}
#define ims_ClipProvisionStatus_init_default     {false, (ims_ClipStatus)0, false, ims_SipErrorInfo_init_default}
#define ims_ServiceClass_init_default            {false, 0}
#define ims_CbNumList_init_default               {false, (ims_ServiceClassStatus)0, {{NULL}, NULL}}
#define ims_CbNumListType_init_default           {false, ims_ServiceClass_init_default, {{NULL}, NULL}}
#define ims_CallWaitingInfo_init_default         {false, (ims_ServiceClassStatus)0, false, ims_ServiceClass_init_default, false, ims_SipErrorInfo_init_default}
#define ims_CallForwardInfoList_init_default     {{{NULL}, NULL}, false, ims_SipErrorInfo_init_default}
#define ims_CallForwardInfoList_CallForwardInfo_init_default {false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, ims_CallFwdTimerInfo_init_default, false, ims_CallFwdTimerInfo_init_default}
#define ims_CallFwdTimerInfo_init_default        {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ims_ConfInfo_init_default                {{{NULL}, NULL}, false, (ims_ConfCallState)0}
#define ims_SuppSvcNotification_init_default     {false, (ims_NotificationType)0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0}
#define ims_SuppSvcStatus_init_default           {false, (ims_ServiceClassStatus)0}
#define ims_SuppSvcRequest_init_default          {false, 0, false, 0, false, ims_CbNumListType_init_default}
#define ims_SuppSvcResponse_init_default         {false, (ims_ServiceClassStatus)0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, ims_SipErrorInfo_init_default}
#define ims_VideoCallQuality_init_default        {false, (ims_Quality)0}
#define ims_MwiMessageSummary_init_default       {false, (ims_MwiMessageType)0, false, 0, false, 0, false, 0, false, 0}
#define ims_MwiMessageDetails_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, (ims_MwiPriority)0, {{NULL}, NULL}, false, (ims_MwiMessageType)0}
#define ims_Mwi_init_default                     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ims_Hold_init_default                    {false, 0}
#define ims_Resume_init_default                  {false, 0}
#define ims_RtpStatisticsData_init_default       {false, 0}
#define ims_WifiCallingInfo_init_default         {false, (ims_WifiCallingStatus)0, false, (ims_WifiCallingPreference)0}
#define ims_ConfigMsg_init_default               {false, (ims_ConfigItem)0, false, 0, false, 0, {{NULL}, NULL}, false, (ims_ConfigFailureCause)0}
#define ims_ViceInfo_init_default                {{{NULL}, NULL}}
#define ims_GeoLocationInfo_init_default         {false, 0, false, 0, false, ims_AddressInfo_init_default}
#define ims_AddressInfo_init_default             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ims_ExplicitCallTransfer_init_default    {false, 0, false, (ims_EctType)0, {{NULL}, NULL}, false, 0}
#define ims_VoWiFiCallQuality_init_default       {false, (ims_voWiFiQuality)0}
#define ims_SsacInfo_init_default                {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ims_VopsInfo_init_default                {false, 0}
#define ims_ParticipantStatusInfo_init_default   {false, 0, false, (ims_ConfParticipantOperation)0, false, 0, {{NULL}, NULL}, false, 0}
#define ims_VolteUserPref_init_default           {false, (ims_VoltePref)0}
#define ims_HandoverConfigMsg_init_default       {false, (ims_HandoverConfig)0}
#define ims_SipErrorInfo_init_default            {false, 0, {{NULL}, NULL}}
#define ims_MsgTag_init_zero                     {0, (ims_MsgType)0, (ims_MsgId)0, (ims_Error)0}
#define ims_CallFailCauseResponse_init_zero      {false, (ims_CallFailCause)0, {{NULL}, NULL}, {{NULL}, NULL}, false, ims_SipErrorInfo_init_zero}
#define ims_StatusForAccessTech_init_zero        {false, (ims_RadioTechType)0, false, (ims_StatusType)0, false, 0, false, ims_Registration_init_zero}
#define ims_Info_init_zero                       {false, 0, false, (ims_SrvType)0, false, (ims_CallType)0, false, (ims_StatusType)0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define ims_SrvStatusList_init_zero              {{{NULL}, NULL}}
#define ims_CallDetails_init_zero                {false, (ims_CallType)0, false, (ims_CallDomain)0, false, 0, {{NULL}, NULL}, false, ims_SrvStatusList_init_zero, false, ims_SrvStatusList_init_zero, false, (ims_CallSubstate)0, false, 0, false, (ims_CauseCodes)0}
#define ims_CallModify_init_zero                 {false, 0, false, ims_CallDetails_init_zero, false, (ims_Error)0}
#define ims_CallList_init_zero                   {{{NULL}, NULL}}
#define ims_CallList_Call_init_zero              {false, (ims_CallState)0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, ims_CallDetails_init_zero, false, ims_CallFailCauseResponse_init_zero, false, 0, false, 0, {{NULL}, NULL}}
#define ims_Colr_init_zero                       {false, (ims_IpPresentation)0, false, ims_SipErrorInfo_init_zero}
#define ims_Dial_init_zero                       {{{NULL}, NULL}, false, 0, false, ims_CallDetails_init_zero, false, (ims_IpPresentation)0, false, 0, false, 0, false, 0}
#define ims_Hangup_init_zero                     {false, 0, false, 0, {{NULL}, NULL}, false, 0, false, ims_CallFailCauseResponse_init_zero}
#define ims_DeflectCall_init_zero                {false, 0, {{NULL}, NULL}}
#define ims_Clir_init_zero                       {false, 0, false, 0}
#define ims_Answer_init_zero                     {false, (ims_CallType)0, false, (ims_IpPresentation)0}
#define ims_SwitchWaitingOrHoldingAndActive_init_zero {false, (ims_CallType)0}
#define ims_Mute_init_zero                       {false, 0}
#define ims_Dtmf_init_zero                       {{{NULL}, NULL}}
#define ims_Registration_init_zero               {false, (ims_Registration_RegState)0, false, 0, {{NULL}, NULL}, false, (ims_RadioTechType)0, {{NULL}, NULL}}
#define ims_RingBackTone_init_zero               {false, (ims_RingBackTone_ToneFlag)0}
#define ims_IFConnected_init_zero                {false, (ims_IFConnected_Version)0}
#define ims_LastFailCause_init_zero              {false, (ims_CallFailCause)0}
#define ims_Extra_init_zero                      {false, (ims_Extra_Type)0, {{NULL}, NULL}}
#define ims_Handover_init_zero                   {false, (ims_Handover_Msg_Type)0, false, (ims_RadioTechType)0, false, (ims_RadioTechType)0, false, ims_Extra_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define ims_TtyNotify_init_zero                  {false, (ims_Tty_Mode_Type)0, {{NULL}, NULL}}
#define ims_RadioStateChanged_init_zero          {false, (ims_RadioState)0}
#define ims_ClipProvisionStatus_init_zero        {false, (ims_ClipStatus)0, false, ims_SipErrorInfo_init_zero}
#define ims_ServiceClass_init_zero               {false, 0}
#define ims_CbNumList_init_zero                  {false, (ims_ServiceClassStatus)0, {{NULL}, NULL}}
#define ims_CbNumListType_init_zero              {false, ims_ServiceClass_init_zero, {{NULL}, NULL}}
#define ims_CallWaitingInfo_init_zero            {false, (ims_ServiceClassStatus)0, false, ims_ServiceClass_init_zero, false, ims_SipErrorInfo_init_zero}
#define ims_CallForwardInfoList_init_zero        {{{NULL}, NULL}, false, ims_SipErrorInfo_init_zero}
#define ims_CallForwardInfoList_CallForwardInfo_init_zero {false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, ims_CallFwdTimerInfo_init_zero, false, ims_CallFwdTimerInfo_init_zero}
#define ims_CallFwdTimerInfo_init_zero           {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ims_ConfInfo_init_zero                   {{{NULL}, NULL}, false, (ims_ConfCallState)0}
#define ims_SuppSvcNotification_init_zero        {false, (ims_NotificationType)0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0}
#define ims_SuppSvcStatus_init_zero              {false, (ims_ServiceClassStatus)0}
#define ims_SuppSvcRequest_init_zero             {false, 0, false, 0, false, ims_CbNumListType_init_zero}
#define ims_SuppSvcResponse_init_zero            {false, (ims_ServiceClassStatus)0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, ims_SipErrorInfo_init_zero}
#define ims_VideoCallQuality_init_zero           {false, (ims_Quality)0}
#define ims_MwiMessageSummary_init_zero          {false, (ims_MwiMessageType)0, false, 0, false, 0, false, 0, false, 0}
#define ims_MwiMessageDetails_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, (ims_MwiPriority)0, {{NULL}, NULL}, false, (ims_MwiMessageType)0}
#define ims_Mwi_init_zero                        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ims_Hold_init_zero                       {false, 0}
#define ims_Resume_init_zero                     {false, 0}
#define ims_RtpStatisticsData_init_zero          {false, 0}
#define ims_WifiCallingInfo_init_zero            {false, (ims_WifiCallingStatus)0, false, (ims_WifiCallingPreference)0}
#define ims_ConfigMsg_init_zero                  {false, (ims_ConfigItem)0, false, 0, false, 0, {{NULL}, NULL}, false, (ims_ConfigFailureCause)0}
#define ims_ViceInfo_init_zero                   {{{NULL}, NULL}}
#define ims_GeoLocationInfo_init_zero            {false, 0, false, 0, false, ims_AddressInfo_init_zero}
#define ims_AddressInfo_init_zero                {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ims_ExplicitCallTransfer_init_zero       {false, 0, false, (ims_EctType)0, {{NULL}, NULL}, false, 0}
#define ims_VoWiFiCallQuality_init_zero          {false, (ims_voWiFiQuality)0}
#define ims_SsacInfo_init_zero                   {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ims_VopsInfo_init_zero                   {false, 0}
#define ims_ParticipantStatusInfo_init_zero      {false, 0, false, (ims_ConfParticipantOperation)0, false, 0, {{NULL}, NULL}, false, 0}
#define ims_VolteUserPref_init_zero              {false, (ims_VoltePref)0}
#define ims_HandoverConfigMsg_init_zero          {false, (ims_HandoverConfig)0}
#define ims_SipErrorInfo_init_zero               {false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ims_AddressInfo_city_tag                 1
#define ims_AddressInfo_state_tag                2
#define ims_AddressInfo_country_tag              3
#define ims_AddressInfo_postalCode_tag           4
#define ims_AddressInfo_countryCode_tag          5
#define ims_CallList_callAttributes_tag          2
#define ims_Dtmf_dtmf_tag                        1
#define ims_Mwi_mwiMsgSummary_tag                1
#define ims_Mwi_ueAddress_tag                    2
#define ims_Mwi_mwiMsgDetail_tag                 3
#define ims_SrvStatusList_SrvStatusInfo_tag      2
#define ims_ViceInfo_vice_info_uri_tag           1
#define ims_Answer_call_type_tag                 1
#define ims_Answer_presentation_tag              4
#define ims_CallDetails_callType_tag             1
#define ims_CallDetails_callDomain_tag           2
#define ims_CallDetails_extrasLength_tag         3
#define ims_CallDetails_extras_tag               4
#define ims_CallDetails_localAbility_tag         5
#define ims_CallDetails_peerAbility_tag          6
#define ims_CallDetails_callSubstate_tag         7
#define ims_CallDetails_mediaId_tag              8
#define ims_CallDetails_causeCode_tag            9
#define ims_CallFwdTimerInfo_year_tag            1
#define ims_CallFwdTimerInfo_month_tag           2
#define ims_CallFwdTimerInfo_day_tag             3
#define ims_CallFwdTimerInfo_hour_tag            4
#define ims_CallFwdTimerInfo_minute_tag          5
#define ims_CallFwdTimerInfo_second_tag          6
#define ims_CallFwdTimerInfo_timezone_tag        7
#define ims_CbNumList_status_tag                 1
#define ims_CbNumList_number_tag                 2
#define ims_Clir_param_m_tag                     1
#define ims_Clir_param_n_tag                     2
#define ims_ConfInfo_conf_info_uri_tag           1
#define ims_ConfInfo_confCallState_tag           2
#define ims_ConfigMsg_item_tag                   1
#define ims_ConfigMsg_boolValue_tag              2
#define ims_ConfigMsg_intValue_tag               3
#define ims_ConfigMsg_stringValue_tag            4
#define ims_ConfigMsg_errorCause_tag             5
#define ims_DeflectCall_conn_index_tag           1
#define ims_DeflectCall_number_tag               2
#define ims_ExplicitCallTransfer_callId_tag      1
#define ims_ExplicitCallTransfer_ectType_tag     2
#define ims_ExplicitCallTransfer_targetAddress_tag 3
#define ims_ExplicitCallTransfer_targetCallId_tag 4
#define ims_Extra_type_tag                       1
#define ims_Extra_extraInfo_tag                  2
#define ims_GeoLocationInfo_lat_tag              1
#define ims_GeoLocationInfo_lon_tag              2
#define ims_GeoLocationInfo_addressInfo_tag      3
#define ims_HandoverConfigMsg_hoConfig_tag       1
#define ims_Hold_callId_tag                      1
#define ims_IFConnected_if_version_tag           1
#define ims_Info_isValid_tag                     1
#define ims_Info_type_tag                        2
#define ims_Info_callType_tag                    3
#define ims_Info_status_tag                      4
#define ims_Info_userdata_tag                    5
#define ims_Info_restrictCause_tag               6
#define ims_Info_accTechStatus_tag               7
#define ims_LastFailCause_cause_tag              1
#define ims_MsgTag_token_tag                     1
#define ims_MsgTag_type_tag                      2
#define ims_MsgTag_id_tag                        3
#define ims_MsgTag_error_tag                     4
#define ims_Mute_mute_flag_tag                   1
#define ims_MwiMessageDetails_toAddress_tag      1
#define ims_MwiMessageDetails_fromAddress_tag    2
#define ims_MwiMessageDetails_subject_tag        3
#define ims_MwiMessageDetails_date_tag           4
#define ims_MwiMessageDetails_priority_tag       5
#define ims_MwiMessageDetails_messageId_tag      6
#define ims_MwiMessageDetails_messageType_tag    7
#define ims_MwiMessageSummary_messageType_tag    1
#define ims_MwiMessageSummary_newMessage_tag     2
#define ims_MwiMessageSummary_oldMessage_tag     3
#define ims_MwiMessageSummary_newUrgent_tag      4
#define ims_MwiMessageSummary_oldUrgent_tag      5
#define ims_ParticipantStatusInfo_callId_tag     1
#define ims_ParticipantStatusInfo_operation_tag  2
#define ims_ParticipantStatusInfo_sipStatus_tag  3
#define ims_ParticipantStatusInfo_participantUri_tag 4
#define ims_ParticipantStatusInfo_isEct_tag      5
#define ims_RadioStateChanged_state_tag          1
#define ims_Registration_state_tag               1
#define ims_Registration_errorCode_tag           2
#define ims_Registration_errorMessage_tag        3
#define ims_Registration_radioTech_tag           4
#define ims_Registration_pAssociatedUris_tag     5
#define ims_Resume_callId_tag                    1
#define ims_RingBackTone_flag_tag                1
#define ims_RtpStatisticsData_count_tag          1
#define ims_ServiceClass_service_Class_tag       1
#define ims_SipErrorInfo_sipErrorCode_tag        1
#define ims_SipErrorInfo_sipErrorString_tag      2
#define ims_SsacInfo_barringFactorVoice_tag      1
#define ims_SsacInfo_barringTimeVoice_tag        2
#define ims_SsacInfo_barringFactorVideo_tag      3
#define ims_SsacInfo_barringTimeVideo_tag        4
#define ims_SsacInfo_barringFactorVoiceSib_tag   5
#define ims_SsacInfo_barringTimeVoiceSib_tag     6
#define ims_SsacInfo_barringFactorVideoSib_tag   7
#define ims_SsacInfo_barringTimeVideoSib_tag     8
#define ims_SuppSvcNotification_notificationType_tag 1
#define ims_SuppSvcNotification_code_tag         2
#define ims_SuppSvcNotification_index_tag        3
#define ims_SuppSvcNotification_type_tag         4
#define ims_SuppSvcNotification_number_tag       5
#define ims_SuppSvcNotification_connId_tag       6
#define ims_SuppSvcNotification_history_info_tag 7
#define ims_SuppSvcNotification_hold_tone_tag    8
#define ims_SuppSvcStatus_status_tag             1
#define ims_SwitchWaitingOrHoldingAndActive_call_type_tag 1
#define ims_TtyNotify_mode_tag                   1
#define ims_TtyNotify_userData_tag               2
#define ims_VideoCallQuality_quality_tag         1
#define ims_VoWiFiCallQuality_quality_tag        1
#define ims_VolteUserPref_mode_tag               1
#define ims_VopsInfo_isVopsEnabled_tag           1
#define ims_WifiCallingInfo_status_tag           1
#define ims_WifiCallingInfo_preference_tag       2
#define ims_CallFailCauseResponse_failcause_tag  1
#define ims_CallFailCauseResponse_errorinfo_tag  2
#define ims_CallFailCauseResponse_networkErrorString_tag 3
#define ims_CallFailCauseResponse_errorDetails_tag 4
#define ims_CallForwardInfoList_info_tag         2
#define ims_CallForwardInfoList_errorDetails_tag 3
#define ims_CallForwardInfoList_CallForwardInfo_status_tag 1
#define ims_CallForwardInfoList_CallForwardInfo_reason_tag 2
#define ims_CallForwardInfoList_CallForwardInfo_service_class_tag 3
#define ims_CallForwardInfoList_CallForwardInfo_toa_tag 4
#define ims_CallForwardInfoList_CallForwardInfo_number_tag 5
#define ims_CallForwardInfoList_CallForwardInfo_time_seconds_tag 6
#define ims_CallForwardInfoList_CallForwardInfo_callFwdTimerStart_tag 7
#define ims_CallForwardInfoList_CallForwardInfo_callFwdTimerEnd_tag 8
#define ims_CallModify_callIndex_tag             2
#define ims_CallModify_callDetails_tag           3
#define ims_CallModify_error_tag                 4
#define ims_CallWaitingInfo_service_status_tag   1
#define ims_CallWaitingInfo_service_class_tag    2
#define ims_CallWaitingInfo_errorDetails_tag     3
#define ims_CbNumListType_serviceClass_tag       1
#define ims_CbNumListType_cb_num_list_tag        2
#define ims_ClipProvisionStatus_clip_status_tag  1
#define ims_ClipProvisionStatus_errorDetails_tag 2
#define ims_Colr_presentation_tag                1
#define ims_Colr_errorDetails_tag                2
#define ims_Dial_address_tag                     1
#define ims_Dial_clir_tag                        2
#define ims_Dial_callDetails_tag                 3
#define ims_Dial_presentation_tag                4
#define ims_Dial_isConferenceUri_tag             5
#define ims_Dial_isCallPull_tag                  6
#define ims_Dial_isEncrypted_tag                 7
#define ims_Handover_type_tag                    1
#define ims_Handover_srcTech_tag                 2
#define ims_Handover_targetTech_tag              3
#define ims_Handover_hoExtra_tag                 4
#define ims_Handover_errorCode_tag               5
#define ims_Handover_errorMessage_tag            6
#define ims_StatusForAccessTech_networkMode_tag  1
#define ims_StatusForAccessTech_status_tag       2
#define ims_StatusForAccessTech_restrictionCause_tag 3
#define ims_StatusForAccessTech_registered_tag   4
#define ims_SuppSvcResponse_status_tag           1
#define ims_SuppSvcResponse_facilityType_tag     2
#define ims_SuppSvcResponse_failureCause_tag     3
#define ims_SuppSvcResponse_cbNumListType_tag    4
#define ims_SuppSvcResponse_errorDetails_tag     5
#define ims_CallList_Call_state_tag              1
#define ims_CallList_Call_index_tag              2
#define ims_CallList_Call_toa_tag                3
#define ims_CallList_Call_isMpty_tag             4
#define ims_CallList_Call_isMT_tag               5
#define ims_CallList_Call_als_tag                6
#define ims_CallList_Call_isVoice_tag            7
#define ims_CallList_Call_isVoicePrivacy_tag     8
#define ims_CallList_Call_number_tag             9
#define ims_CallList_Call_numberPresentation_tag 10
#define ims_CallList_Call_name_tag               11
#define ims_CallList_Call_namePresentation_tag   12
#define ims_CallList_Call_callDetails_tag        13
#define ims_CallList_Call_failCause_tag          14
#define ims_CallList_Call_isEncrypted_tag        15
#define ims_CallList_Call_isCalledPartyRinging_tag 16
#define ims_CallList_Call_historyInfo_tag        17
#define ims_Hangup_conn_index_tag                1
#define ims_Hangup_multi_party_tag               2
#define ims_Hangup_conn_uri_tag                  3
#define ims_Hangup_conf_id_tag                   4
#define ims_Hangup_failCauseResponse_tag         5
#define ims_SuppSvcRequest_operationType_tag     1
#define ims_SuppSvcRequest_facilityType_tag      2
#define ims_SuppSvcRequest_cbNumListType_tag     3

/* Struct field encoding specification for nanopb */
extern const pb_field_t ims_MsgTag_fields[5];
extern const pb_field_t ims_CallFailCauseResponse_fields[5];
extern const pb_field_t ims_StatusForAccessTech_fields[5];
extern const pb_field_t ims_Info_fields[8];
extern const pb_field_t ims_SrvStatusList_fields[2];
extern const pb_field_t ims_CallDetails_fields[10];
extern const pb_field_t ims_CallModify_fields[4];
extern const pb_field_t ims_CallList_fields[2];
extern const pb_field_t ims_CallList_Call_fields[18];
extern const pb_field_t ims_Colr_fields[3];
extern const pb_field_t ims_Dial_fields[8];
extern const pb_field_t ims_Hangup_fields[6];
extern const pb_field_t ims_DeflectCall_fields[3];
extern const pb_field_t ims_Clir_fields[3];
extern const pb_field_t ims_Answer_fields[3];
extern const pb_field_t ims_SwitchWaitingOrHoldingAndActive_fields[2];
extern const pb_field_t ims_Mute_fields[2];
extern const pb_field_t ims_Dtmf_fields[2];
extern const pb_field_t ims_Registration_fields[6];
extern const pb_field_t ims_RingBackTone_fields[2];
extern const pb_field_t ims_IFConnected_fields[2];
extern const pb_field_t ims_LastFailCause_fields[2];
extern const pb_field_t ims_Extra_fields[3];
extern const pb_field_t ims_Handover_fields[7];
extern const pb_field_t ims_TtyNotify_fields[3];
extern const pb_field_t ims_RadioStateChanged_fields[2];
extern const pb_field_t ims_ClipProvisionStatus_fields[3];
extern const pb_field_t ims_ServiceClass_fields[2];
extern const pb_field_t ims_CbNumList_fields[3];
extern const pb_field_t ims_CbNumListType_fields[3];
extern const pb_field_t ims_CallWaitingInfo_fields[4];
extern const pb_field_t ims_CallForwardInfoList_fields[3];
extern const pb_field_t ims_CallForwardInfoList_CallForwardInfo_fields[9];
extern const pb_field_t ims_CallFwdTimerInfo_fields[8];
extern const pb_field_t ims_ConfInfo_fields[3];
extern const pb_field_t ims_SuppSvcNotification_fields[9];
extern const pb_field_t ims_SuppSvcStatus_fields[2];
extern const pb_field_t ims_SuppSvcRequest_fields[4];
extern const pb_field_t ims_SuppSvcResponse_fields[6];
extern const pb_field_t ims_VideoCallQuality_fields[2];
extern const pb_field_t ims_MwiMessageSummary_fields[6];
extern const pb_field_t ims_MwiMessageDetails_fields[8];
extern const pb_field_t ims_Mwi_fields[4];
extern const pb_field_t ims_Hold_fields[2];
extern const pb_field_t ims_Resume_fields[2];
extern const pb_field_t ims_RtpStatisticsData_fields[2];
extern const pb_field_t ims_WifiCallingInfo_fields[3];
extern const pb_field_t ims_ConfigMsg_fields[6];
extern const pb_field_t ims_ViceInfo_fields[2];
extern const pb_field_t ims_GeoLocationInfo_fields[4];
extern const pb_field_t ims_AddressInfo_fields[6];
extern const pb_field_t ims_ExplicitCallTransfer_fields[5];
extern const pb_field_t ims_VoWiFiCallQuality_fields[2];
extern const pb_field_t ims_SsacInfo_fields[9];
extern const pb_field_t ims_VopsInfo_fields[2];
extern const pb_field_t ims_ParticipantStatusInfo_fields[6];
extern const pb_field_t ims_VolteUserPref_fields[2];
extern const pb_field_t ims_HandoverConfigMsg_fields[2];
extern const pb_field_t ims_SipErrorInfo_fields[3];

/* Maximum encoded size of messages (where known) */
#define ims_MsgTag_size                          12
/* ims_CallFailCauseResponse_size depends on runtime parameters */
#define ims_StatusForAccessTech_size             (24 + ims_Registration_size)
/* ims_Info_size depends on runtime parameters */
/* ims_SrvStatusList_size depends on runtime parameters */
/* ims_CallDetails_size depends on runtime parameters */
#define ims_CallModify_size                      (13 + ims_CallDetails_size)
/* ims_CallList_size depends on runtime parameters */
/* ims_CallList_Call_size depends on runtime parameters */
#define ims_Colr_size                            (8 + ims_SipErrorInfo_size)
/* ims_Dial_size depends on runtime parameters */
/* ims_Hangup_size depends on runtime parameters */
/* ims_DeflectCall_size depends on runtime parameters */
#define ims_Clir_size                            10
#define ims_Answer_size                          4
#define ims_SwitchWaitingOrHoldingAndActive_size 2
#define ims_Mute_size                            2
/* ims_Dtmf_size depends on runtime parameters */
/* ims_Registration_size depends on runtime parameters */
#define ims_RingBackTone_size                    2
#define ims_IFConnected_size                     2
#define ims_LastFailCause_size                   4
/* ims_Extra_size depends on runtime parameters */
/* ims_Handover_size depends on runtime parameters */
/* ims_TtyNotify_size depends on runtime parameters */
#define ims_RadioStateChanged_size               2
#define ims_ClipProvisionStatus_size             (8 + ims_SipErrorInfo_size)
#define ims_ServiceClass_size                    5
/* ims_CbNumList_size depends on runtime parameters */
/* ims_CbNumListType_size depends on runtime parameters */
#define ims_CallWaitingInfo_size                 (15 + ims_SipErrorInfo_size)
/* ims_CallForwardInfoList_size depends on runtime parameters */
/* ims_CallForwardInfoList_CallForwardInfo_size depends on runtime parameters */
#define ims_CallFwdTimerInfo_size                35
/* ims_ConfInfo_size depends on runtime parameters */
/* ims_SuppSvcNotification_size depends on runtime parameters */
#define ims_SuppSvcStatus_size                   2
#define ims_SuppSvcRequest_size                  (16 + ims_CbNumListType_size)
/* ims_SuppSvcResponse_size depends on runtime parameters */
#define ims_VideoCallQuality_size                2
#define ims_MwiMessageSummary_size               31
/* ims_MwiMessageDetails_size depends on runtime parameters */
/* ims_Mwi_size depends on runtime parameters */
#define ims_Hold_size                            5
#define ims_Resume_size                          5
#define ims_RtpStatisticsData_size               5
#define ims_WifiCallingInfo_size                 4
/* ims_ConfigMsg_size depends on runtime parameters */
/* ims_ViceInfo_size depends on runtime parameters */
#define ims_GeoLocationInfo_size                 (24 + ims_AddressInfo_size)
/* ims_AddressInfo_size depends on runtime parameters */
/* ims_ExplicitCallTransfer_size depends on runtime parameters */
#define ims_VoWiFiCallQuality_size               2
#define ims_SsacInfo_size                        40
#define ims_VopsInfo_size                        2
/* ims_ParticipantStatusInfo_size depends on runtime parameters */
#define ims_VolteUserPref_size                   2
#define ims_HandoverConfigMsg_size               2
/* ims_SipErrorInfo_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define IMSIF_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
